In [ ]:
#IMPORT LIBRARIES

import pandas as pd
import numpy as np

print("Setup Successful")

Setup Successful

In [ ]:
#Load the Dataset

import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
# Data Cleaning
# Check missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
# Check blank spaces in TotalCharges
(df['TotalCharges'] == ' ').sum()

np.int64(11)

In [ ]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [ ]:
df['TotalCharges'].isnull().sum()

np.int64(11)

In [ ]:
df = df.dropna()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Total Customers
total_customers = len(df)
print("Total Customers:", total_customers)

# Churned Customers
churned = len(df[df['Churn'] == 'Yes'])
print("Churned Customers:", churned)

# Retained Customers
retained = len(df[df['Churn'] == 'No'])
print("Retained Customers:", retained)

# Churn Rate
churn_rate = (churned / total_customers) * 100
print("Churn Rate:", round(churn_rate,2), "%")

# Retention Rate
retention_rate = (retained / total_customers) * 100
print("Retention Rate:", round(retention_rate,2), "%")

Total Customers: 7032
Churned Customers: 1869
Retained Customers: 5163
Churn Rate: 26.58 %
Retention Rate: 73.42 %

In [ ]:
print("Average Monthly Charges:", round(df['MonthlyCharges'].mean(),2))

print("Average Customer Lifetime (Months):", round(df['tenure'].mean(),2))

print("Total Revenue:", round(df['TotalCharges'].sum(),2))

Average Monthly Charges: 64.8
Average Customer Lifetime (Months): 32.42
Total Revenue: 16056168.7

In [ ]:
#contract churn analysis
pd.crosstab(df['Contract'], df['Churn'], normalize='index') * 100

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.722826  11.277174
Two year        97.151335   2.848665

In [ ]:
#internetservice churn analysis
pd.crosstab(df['InternetService'], df['Churn'], normalize='index') * 100

Churn                   No        Yes
InternetService
DSL              81.001656  18.998344
Fiber optic      58.107235  41.892765
No               92.565789   7.434211

In [ ]:
#payment method churn analysis
pd.crosstab(df['PaymentMethod'], df['Churn'], normalize='index') * 100

Churn                             No        Yes
PaymentMethod
Bank transfer (automatic)  83.268482  16.731518
Credit card (automatic)    84.746877  15.253123
Electronic check           54.714588  45.285412
Mailed check               80.798005  19.201995

In [ ]:
#seniorcitizen churn analysis
pd.crosstab(df['SeniorCitizen'], df['Churn'], normalize='index') * 100

Churn                 No        Yes
SeniorCitizen
0              76.349745  23.650255
1              58.318739  41.681261

In [ ]:
#partner churn analysis
pd.crosstab(df['Partner'], df['Churn'], normalize='index') * 100

Churn           No        Yes
Partner
No       67.023908  32.976092
Yes      80.282935  19.717065

In [ ]:
#dependents churn analysis
pd.crosstab(df['Dependents'], df['Churn'], normalize='index') * 100

Churn              No        Yes
Dependents
No          68.720860  31.279140
Yes         84.468795  15.531205