In [ ]:
#IMPORT LIBRARIES

import pandas as pd
import numpy as np

print("Setup Successful")

Setup Successful

In [ ]:
#LOAD DATASET

from google.colab import files

uploaded = files.upload()

Saving bank-additional-full.csv to bank-additional-full.csv

In [ ]:
import pandas as pd

df = pd.read_csv("bank-additional-full.csv", sep=';')

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [ ]:
df.shape

(41188, 21)

In [ ]:
df['y'].value_counts()

y
no     36548
yes     4640
Name: count, dtype: int64

In [ ]:
# Data Cleaning
# Check missing values
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [ ]:
#KPI METRICS
total_customers = len(df)

converted = len(df[df['y']=='yes'])

not_converted = len(df[df['y']=='no'])

conversion_rate = (converted/total_customers)*100

print("Total Customers:", total_customers)
print("Converted Customers:", converted)
print("Not Converted:", not_converted)
print("Conversion Rate:", round(conversion_rate,2), "%")

Total Customers: 41188
Converted Customers: 4640
Not Converted: 36548
Conversion Rate: 11.27 %

In [ ]:
#Conversion by Contact Type
pd.crosstab(df['contact'],df['y'],normalize='index')*100

y                 no        yes
contact
cellular   85.262393  14.737607
telephone  94.768679   5.231321

In [ ]:
#Conversion by Month
pd.crosstab(df['month'],df['y'],normalize='index')*100

y             no        yes
month
apr    79.521277  20.478723
aug    89.397863  10.602137
dec    51.098901  48.901099
jul    90.953443   9.046557
jun    89.488530  10.511470
mar    49.450549  50.549451
may    93.565255   6.434745
nov    89.856133  10.143867
oct    56.128134  43.871866
sep    55.087719  44.912281

In [ ]:
#Conversion by Job
pd.crosstab(df['job'],df['y'],normalize='index')*100

y                     no        yes
job
admin.         87.027442  12.972558
blue-collar    93.105684   6.894316
entrepreneur   91.483516   8.516484
housemaid      90.000000  10.000000
management     88.782490  11.217510
retired        74.767442  25.232558
self-employed  89.514426  10.485574
services       91.861930   8.138070
student        68.571429  31.428571
technician     89.173958  10.826042
unemployed     85.798817  14.201183
unknown        88.787879  11.212121

In [ ]:
#Conversion by Education
pd.crosstab(df['education'],df['y'],normalize='index')*100

y                           no        yes
education
basic.4y             89.750958  10.249042
basic.6y             91.797557   8.202443
basic.9y             92.175352   7.824648
high.school          89.164477  10.835523
illiterate           77.777778  22.222222
professional.course  88.651535  11.348465
university.degree    86.275477  13.724523
unknown              85.499711  14.500289

In [ ]:
#Conversion by Previous Campaign Outcome
pd.crosstab(df['poutcome'],df['y'],normalize='index')*100

y                   no        yes
poutcome
failure      85.771402  14.228598
nonexistent  91.167787   8.832213
success      34.887109  65.112891